name: GitHub Action with Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot APP
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run Unit tests
        run:  mvn -B test --file pom.xml

      - name: Build & Package application
        run: | 
          mvn clean
          mvn -B package --file pom.xml

      - name: Build & Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          image: lakshitha200/springboot-github-action-secondway
          tags: v1
          registry: docker.io
          context: .
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
